conn l2tp-client
    keyexchange=ikev1
    authby=secret
    type=transport
    left=%defaultroute
    leftprotoport=17/1701
    right=VPN_IP
    rightprotoport=17/1701

    ike=aes256-sha256-modp2048,aes128-sha256-modp2048,aes256-sha1-modp2048,aes128-sha1-modp2048
    esp=aes256-sha256,aes128-sha256,aes256-sha512,aes256-sha1,aes128-sha1
    encapsulation=yes
    fragmentation=yes
    auto=route
